#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

INSTALL_ZSH=1
INSTALL_TMUX=1
INSTALL_NVIM=1
INSTALL_OPENCODE=1
INSTALL_CLAUDE=1

log() {
  printf "\n[dotfiles] %s\n" "$1"
}

need_sudo() {
  if [[ "${EUID}" -ne 0 ]]; then
    sudo "$@"
  else
    "$@"
  fi
}

have_apt_package() {
  apt-cache show "$1" >/dev/null 2>&1
}

backup_file() {
  local target="$1"
  if [[ -e "$target" || -L "$target" ]]; then
    local backup="${target}.bak.$(date +%Y%m%d%H%M%S)"
    mv "$target" "$backup"
    log "Backed up $target -> $backup"
  fi
}

link_file() {
  local src="$1"
  local dst="$2"
  if [[ -L "$dst" ]] && [[ "$(readlink "$dst")" == "$src" ]]; then
    return 0
  fi
  mkdir -p "$(dirname "$dst")"
  backup_file "$dst"
  ln -s "$src" "$dst"
  log "Linked $dst"
}

# Prompts are skipped (everything installs with defaults) when running
# non-interactively, e.g. curl | bash, or when --all / -y is passed.
is_interactive() {
  [[ "${ASSUME_ALL}" -eq 0 ]] && [[ -t 0 ]]
}

select_components() {
  is_interactive || return 0

  cat <<'EOF'

Select components to install:
  1) zsh       Oh My Zsh, Oh My Posh, .zshrc
  2) tmux      config, TPM plugins, workspace launcher
  3) neovim    latest release, LazyVim config
  4) opencode  OpenCode CLI
  5) claude    Claude Code CLI
EOF
  printf "Enter numbers separated by spaces, or press Enter for all: "
  local selection token
  read -r selection
  [[ -z "$selection" ]] && return 0

  INSTALL_ZSH=0
  INSTALL_TMUX=0
  INSTALL_NVIM=0
  INSTALL_OPENCODE=0
  INSTALL_CLAUDE=0
  for token in ${selection//,/ }; do
    case "$token" in
      1) INSTALL_ZSH=1 ;;
      2) INSTALL_TMUX=1 ;;
      3) INSTALL_NVIM=1 ;;
      4) INSTALL_OPENCODE=1 ;;
      5) INSTALL_CLAUDE=1 ;;
      *) log "Ignoring unknown selection: $token" ;;
    esac
  done
}

configure_tmux_tabs() {
  is_interactive || return 0

  cat <<'EOF'

Default tmux workspace tabs:
  code, codex (opencode), claude (claude), terminal, monitoring (btop), misc
EOF
  printf "Use default tabs? [Y/n]: "
  local answer
  read -r answer
  case "$answer" in
    n|N|no|NO) ;;
    *) return 0 ;;
  esac

  log "Define your tabs. Format: name or name:command. Empty line to finish."
  local tabs=() line
  while true; do
    printf "Tab %d: " "$(( ${#tabs[@]} + 1 ))"
    read -r line
    [[ -z "$line" ]] && break
    tabs+=("$line")
  done

  if [[ ${#tabs[@]} -eq 0 ]]; then
    log "No tabs entered; keeping defaults"
    return 0
  fi

  local config="$HOME/.tmux-workspace.conf"
  backup_file "$config"
  {
    echo "# tmux workspace tabs: name or name:command"
    echo "# Generated by dotfiles install.sh; edit freely."
    echo "session_name=workspace"
    echo "attach_existing=1"
    local tab
    for tab in "${tabs[@]}"; do
      echo "$tab"
    done
  } > "$config"
  log "Wrote $config"
}

install_base_packages() {
  log "Installing base packages"
  local packages=(
    git curl wget unzip build-essential ca-certificates
    python3 python3-pip ripgrep fd-find fzf btop
  )
  [[ "$INSTALL_ZSH" -eq 1 ]] && packages+=(zsh)
  [[ "$INSTALL_TMUX" -eq 1 ]] && packages+=(tmux)

  need_sudo apt update
  need_sudo apt install -y "${packages[@]}"

  if have_apt_package eza; then
    need_sudo apt install -y eza
  fi
}

install_latest_neovim() {
  log "Installing latest Neovim"
  local tmp_dir
  local arch
  local archive
  local extracted_dir
  tmp_dir="$(mktemp -d)"
  arch="$(uname -m)"
  case "$arch" in
    x86_64)
      archive="nvim-linux-x86_64.tar.gz"
      extracted_dir="nvim-linux-x86_64"
      ;;
    aarch64|arm64)
      archive="nvim-linux-arm64.tar.gz"
      extracted_dir="nvim-linux-arm64"
      ;;
    *)
      log "Unsupported architecture for automatic Neovim install: $arch"
      return 1
      ;;
  esac
  curl -fsSL -o "$tmp_dir/nvim.tar.gz" "https://github.com/neovim/neovim/releases/latest/download/$archive"
  need_sudo rm -rf /opt/nvim
  need_sudo tar -C /opt -xzf "$tmp_dir/nvim.tar.gz"
  need_sudo mv "/opt/$extracted_dir" /opt/nvim
  need_sudo ln -sf /opt/nvim/bin/nvim /usr/local/bin/nvim
  rm -rf "$tmp_dir"
}

install_oh_my_zsh() {
  if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
    log "Installing Oh My Zsh"
    RUNZSH=no CHSH=no KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  else
    log "Oh My Zsh already installed"
  fi

  local custom_plugins="$HOME/.oh-my-zsh/custom/plugins"
  mkdir -p "$custom_plugins"

  if [[ ! -d "$custom_plugins/zsh-autosuggestions" ]]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions "$custom_plugins/zsh-autosuggestions"
  fi
  if [[ ! -d "$custom_plugins/zsh-syntax-highlighting" ]]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting "$custom_plugins/zsh-syntax-highlighting"
  fi
}

install_oh_my_posh() {
  if ! command -v oh-my-posh >/dev/null 2>&1; then
    log "Installing Oh My Posh"
    mkdir -p "$HOME/.local/bin"
    curl -fsSL https://ohmyposh.dev/install.sh | bash -s -- -d "$HOME/.local/bin"
  else
    log "Oh My Posh already installed"
  fi
}

install_opencode() {
  if ! command -v opencode >/dev/null 2>&1; then
    log "Installing OpenCode"
    curl -fsSL https://opencode.ai/install | bash
  else
    log "OpenCode already installed"
  fi
}

install_claude_code() {
  if ! command -v claude >/dev/null 2>&1; then
    log "Installing Claude Code"
    curl -fsSL https://claude.ai/install.sh | bash
  else
    log "Claude Code already installed"
  fi
}

install_tpm() {
  if [[ ! -d "$HOME/.tmux/plugins/tpm" ]]; then
    log "Installing TPM"
    git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
  else
    log "TPM already installed"
  fi
}

install_tmux_plugins() {
  log "Installing tmux plugins"
  "$HOME/.tmux/plugins/tpm/bin/install_plugins"
}

bootstrap_nvim_plugins() {
  log "Bootstrapping LazyVim plugins"
  nvim --headless "+Lazy! sync" +qa
}

set_default_shell() {
  local current_shell
  local target_shell
  current_shell="$(getent passwd "$USER" | cut -d: -f7)"
  target_shell="$(command -v zsh)"
  if [[ "$current_shell" != "$target_shell" ]]; then
    log "Setting zsh as default shell (may ask password)"
    chsh -s "$target_shell"
  fi
}

main() {
  ASSUME_ALL=0
  local arg
  for arg in "$@"; do
    case "$arg" in
      --all|-y|--yes) ASSUME_ALL=1 ;;
    esac
  done

  select_components
  if [[ "$INSTALL_TMUX" -eq 1 ]]; then
    configure_tmux_tabs
  fi

  install_base_packages

  if [[ "$INSTALL_NVIM" -eq 1 ]]; then
    install_latest_neovim
  fi
  if [[ "$INSTALL_ZSH" -eq 1 ]]; then
    install_oh_my_zsh
    install_oh_my_posh
  fi
  if [[ "$INSTALL_OPENCODE" -eq 1 ]]; then
    install_opencode
  fi
  if [[ "$INSTALL_CLAUDE" -eq 1 ]]; then
    install_claude_code
  fi
  if [[ "$INSTALL_TMUX" -eq 1 ]]; then
    install_tpm
  fi

  log "Linking dotfiles"
  mkdir -p "$HOME/.local/bin"

  if [[ "$INSTALL_ZSH" -eq 1 ]]; then
    link_file "$ROOT_DIR/zsh/.zshrc" "$HOME/.zshrc"
    link_file "$ROOT_DIR/zsh/.zprofile" "$HOME/.zprofile"
    mkdir -p "$HOME/omp-config"
    link_file "$ROOT_DIR/omp-config/myconfig.json" "$HOME/omp-config/myconfig.json"
  fi

  if [[ "$INSTALL_TMUX" -eq 1 ]]; then
    link_file "$ROOT_DIR/tmux/.tmux.conf" "$HOME/.tmux.conf"
    link_file "$ROOT_DIR/tmux/start-workspace.sh" "$HOME/.local/bin/start-tmux-workspace"
  fi

  if [[ "$INSTALL_NVIM" -eq 1 ]]; then
    mkdir -p "$HOME/.config"
    link_file "$ROOT_DIR/nvim" "$HOME/.config/nvim"
  fi

  if [[ "$INSTALL_OPENCODE" -eq 1 ]]; then
    mkdir -p "$HOME/.config/opencode"
    link_file "$ROOT_DIR/opencode/opencode.jsonc" "$HOME/.config/opencode/opencode.jsonc"
  fi

  if [[ "$INSTALL_TMUX" -eq 1 ]]; then
    install_tmux_plugins
  fi
  if [[ "$INSTALL_NVIM" -eq 1 ]]; then
    bootstrap_nvim_plugins
  fi
  if [[ "$INSTALL_ZSH" -eq 1 ]]; then
    set_default_shell
  fi

  log "Done. Restart terminal or run: exec zsh"
  printf "sh setup completed\n"
}

main "$@"
